In [1]:
# importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the data
r_cols =['user_id','movie_id','rating','unic_timestamp']
ratings= pd.read_csv('ml-100K/u.data',sep='\t',names=r_cols,encoding='latin-1')
ratings

       user_id  movie_id  rating  unic_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [3]:
#Loading the movie data
i_cols=['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item',sep='|',names = i_cols, encoding='latin-1')
items.head(3)

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [4]:
#select only needed item
movie_content = items[['movie id','movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]
movie_content

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [5]:
#Here we are counting and calculating mean 
movie_stats = ratings.groupby('movie_id')['rating'].agg(['count', 'mean']).reset_index()
movie_stats.head()

   movie_id  count      mean
0         1    452  3.878319
1         2    131  3.206107
2         3     90  3.033333
3         4    209  3.550239
4         5     86  3.302326

In [6]:
movie_content = movie_content.rename(columns={'movie id': 'movie_id'})

#Merge movie stats and movie content dataframes on movie_id
movie_data = pd.merge(movie_stats, movie_content, on='movie_id')
movie_data.head()

,movie_id,count,mean,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,452,3.878319,Toy Story (1995),0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,131,3.206107,GoldenEye (1995),1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,90,3.033333,Four Rooms (1995),0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,209,3.550239,Get Shorty (1995),1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,5,86,3.302326,Copycat (1995),0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [7]:
genres = movie_content.columns[2:]
genres

Index(['Action', 'Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [8]:
# Checking for 1 gener
top5_movies_by_genre = {}

for genre in genres:
    genre_movies = movie_data[movie_data[genre] == 1]
    
    top5 = genre_movies.sort_values(
        by=['count', 'mean'], 
        ascending=False
    ).head(5)[['movie_id', 'movie title', 'count', 'mean']]
    
    top5_movies_by_genre[genre] = top5

top5_movies_by_genre['Adventure']

     movie_id                      movie title  count      mean
49         50                 Star Wars (1977)    583  4.358491
180       181        Return of the Jedi (1983)    507  4.007890
173       174   Raiders of the Lost Ark (1981)    420  4.252381
116       117                 Rock, The (1996)    378  3.693122
171       172  Empire Strikes Back, The (1980)    367  4.204360

In [9]:
def recommend_by_genre(user_genre=None):

    if user_genre and user_genre in top5_movies_by_genre:
        print(f"\nTop 5 popular movies in {user_genre}:\n")
        return top5_movies_by_genre[user_genre]

    else:
        print("\nTop 5 popular movies from each genre:")
        
        for genre, df in top5_movies_by_genre.items():
            print(genre)
            display(df)

In [10]:
recommend_by_genre()

Top 5 popular movies from each genre:
Action

     movie_id                     movie title  count      mean
49         50                Star Wars (1977)    583  4.358491
180       181       Return of the Jedi (1983)    507  4.007890
299       300            Air Force One (1997)    431  3.631090
120       121   Independence Day (ID4) (1996)    429  3.438228
173       174  Raiders of the Lost Ark (1981)    420  4.252381

Adventure

     movie_id                      movie title  count      mean
49         50                 Star Wars (1977)    583  4.358491
180       181        Return of the Jedi (1983)    507  4.007890
173       174   Raiders of the Lost Ark (1981)    420  4.252381
116       117                 Rock, The (1996)    378  3.693122
171       172  Empire Strikes Back, The (1980)    367  4.204360

Animation

     movie_id                  movie title  count      mean
0           1             Toy Story (1995)    452  3.878319
70         71        Lion King, The (1994)    220  3.781818
94         95               Aladdin (1992)    219  3.812785
587       588  Beauty and the Beast (1991)    202  3.792079
431       432              Fantasia (1940)    174  3.770115

Children's

     movie_id                                   movie title  count      mean
0           1                              Toy Story (1995)    452  3.878319
150       151  Willy Wonka and the Chocolate Factory (1971)    326  3.631902
422       423             E.T. the Extra-Terrestrial (1982)    300  3.833333
131       132                      Wizard of Oz, The (1939)    246  4.077236
70         71                         Lion King, The (1994)    220  3.781818

Comedy

     movie_id                                   movie title  count      mean
293       294                              Liar Liar (1997)    485  3.156701
0           1                              Toy Story (1995)    452  3.878319
203       204                     Back to the Future (1985)    350  3.834286
150       151  Willy Wonka and the Chocolate Factory (1971)    326  3.631902
172       173                    Princess Bride, The (1987)    324  4.172840

Crime

     movie_id                 movie title  count      mean
99        100                Fargo (1996)    508  4.155512
126       127       Godfather, The (1972)    413  4.283293
55         56         Pulp Fiction (1994)    394  4.060914
301       302    L.A. Confidential (1997)    297  4.161616
11         12  Usual Suspects, The (1995)    267  4.385768

Documentary

      movie_id                   movie title  count      mean
47          48            Hoop Dreams (1994)    117  4.094017
31          32                  Crumb (1994)     81  3.790123
812        813  Celluloid Closet, The (1995)     56  3.892857
846        847    Looking for Richard (1996)     55  3.727273
1064      1065          Koyaanisqatsi (1983)     53  3.490566

Drama

     movie_id                  movie title  count      mean
257       258               Contact (1997)    509  3.803536
99        100                 Fargo (1996)    508  4.155512
285       286  English Patient, The (1996)    481  3.656965
126       127        Godfather, The (1972)    413  4.283293
55         56          Pulp Fiction (1994)    394  4.060914

Fantasy

     movie_id                        movie title  count      mean
422       423  E.T. the Extra-Terrestrial (1982)    300  3.833333
410       411        Nutty Professor, The (1996)    163  2.914110
471       472                 Dragonheart (1996)    158  3.082278
71         72                   Mask, The (1994)    129  3.193798
754       755                     Jumanji (1995)     96  3.312500

Film-Noir

     movie_id                       movie title  count      mean
301       302          L.A. Confidential (1997)    297  4.161616
88         89               Blade Runner (1982)    275  4.138182
653       654                  Chinatown (1974)    147  4.136054
483       484        Maltese Falcon, The (1941)    138  4.210145
656       657  Manchurian Candidate, The (1962)    131  4.259542

Horror

     movie_id          movie title  count      mean
287       288        Scream (1996)    478  3.441423
182       183         Alien (1979)    291  4.034364
233       234          Jaws (1975)    280  3.775000
184       185        Psycho (1960)    239  4.100418
199       200  Shining, The (1980)    206  3.825243

Musical

     movie_id                 movie title  count      mean
288       289                Evita (1996)    259  2.980695
185       186  Blues Brothers, The (1980)    251  3.836653
131       132    Wizard of Oz, The (1939)    246  4.077236
142       143  Sound of Music, The (1965)    222  3.765766
70         71       Lion King, The (1994)    220  3.781818

Mystery

     movie_id                   movie title  count      mean
404       405    Mission: Impossible (1996)    344  3.313953
301       302      L.A. Confidential (1997)    297  4.161616
327       328      Conspiracy Theory (1997)    295  3.423729
190       191                Amadeus (1984)    276  4.163043
134       135  2001: A Space Odyssey (1968)    259  3.969112

Romance

     movie_id                      movie title  count      mean
49         50                 Star Wars (1977)    583  4.358491
180       181        Return of the Jedi (1983)    507  4.007890
285       286      English Patient, The (1996)    481  3.656965
236       237             Jerry Maguire (1996)    384  3.710938
171       172  Empire Strikes Back, The (1980)    367  4.204360

Sci-Fi

     movie_id                    movie title  count      mean
49         50               Star Wars (1977)    583  4.358491
257       258                 Contact (1997)    509  3.803536
180       181      Return of the Jedi (1983)    507  4.007890
120       121  Independence Day (ID4) (1996)    429  3.438228
6           7          Twelve Monkeys (1995)    392  3.798469

Thriller

     movie_id                       movie title  count      mean
99        100                      Fargo (1996)    508  4.155512
287       288                     Scream (1996)    478  3.441423
299       300              Air Force One (1997)    431  3.631090
97         98  Silence of the Lambs, The (1991)    390  4.289744
116       117                  Rock, The (1996)    378  3.693122

War

     movie_id                      movie title  count      mean
49         50                 Star Wars (1977)    583  4.358491
180       181        Return of the Jedi (1983)    507  4.007890
285       286      English Patient, The (1996)    481  3.656965
120       121    Independence Day (ID4) (1996)    429  3.438228
171       172  Empire Strikes Back, The (1980)    367  4.204360

Western

     movie_id                                movie title  count      mean
96         97                  Dances with Wolves (1990)    256  3.792969
434       435  Butch Cassidy and the Sundance Kid (1969)    216  3.949074
202       203                          Unforgiven (1992)    182  3.868132
176       177     Good, The Bad and The Ugly, The (1966)    137  3.861314
72         73                            Maverick (1994)    128  3.468750